# Generated by Django 6.1 on 2026-09-01 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('workspace_type', models.CharField(choices=[('HOUSEHOLD', 'Household / Family'), ('BUSINESS', 'Business / Project Team'), ('CONSTRUCTION', 'Construction Project'), ('EDUCATION', 'Education / Student Group'), ('COMMUNITY', 'Community'), ('ORGANIZATION', 'Organization'), ('SPORTS_TEAM', 'Sports Team'), ('OTHER', 'Other')], max_length=32)),
                ('custom_workspace_type', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=16)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_templates', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='tasks.workspace')),
            ],
            options={
                'ordering': ['workspace_id', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_type', models.CharField(blank=True, choices=[('SELF_SELECTION', 'Self-selection'), ('MANAGER_ASSIGNMENT', 'Manager assignment'), ('REASSIGNMENT', 'Reassignment')], max_length=32, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING_ACCEPTANCE', 'Pending acceptance'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('GRACE_PERIOD', 'Grace period'), ('INCOMPLETE', 'Incomplete'), ('PENDING_REASSIGNMENT', 'Pending reassignment'), ('REJECTED', 'Rejected')], default='AVAILABLE', max_length=32)),
                ('title_snapshot', models.CharField(max_length=255)),
                ('description_snapshot', models.TextField(blank=True)),
                ('frequency_snapshot', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=16)),
                ('difficulty_snapshot', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=16)),
                ('completion_points_snapshot', models.IntegerField(blank=True, null=True)),
                ('late_penalty_snapshot', models.IntegerField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_task_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_task_assignments', to=settings.AUTH_USER_MODEL)),
                ('task_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='tasks.tasktemplate')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='tasks.workspace')),
            ],
            options={
                'ordering': ['workspace_id', 'status', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskEventHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TASK_CREATED', 'Task created'), ('TASK_BECAME_AVAILABLE', 'Task became available'), ('MEMBER_SELECTED_TASK', 'Member selected task'), ('MANAGER_ASSIGNED_TASK', 'Manager assigned task'), ('MEMBER_ACCEPTED_ASSIGNMENT', 'Member accepted assignment'), ('MEMBER_REJECTED_ASSIGNMENT', 'Member rejected assignment'), ('TASK_BECAME_OVERDUE', 'Task became overdue'), ('LATE_PENALTY_APPLIED', 'Late penalty applied'), ('GRACE_PERIOD_STARTED', 'Grace period started'), ('TASK_COMPLETED', 'Task completed'), ('TASK_BECAME_INCOMPLETE', 'Task became incomplete'), ('TASK_REASSIGNED', 'Task reassigned'), ('DAILY_TASK_ROLLED_OVER', 'Daily task rolled over')], max_length=40)),
                ('score_change', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_history_actions', to=settings.AUTH_USER_MODEL)),
                ('affected_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_history_memberships', to=settings.AUTH_USER_MODEL)),
                ('task_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='tasks.taskassignment')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_history_events', to='tasks.workspace')),
            ],
            options={
                'ordering': ['task_assignment_id', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('MEMBER', 'Member')], max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tasks.workspace')),
            ],
            options={
                'ordering': ['workspace_id', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'user'), name='unique_membership_per_workspace_user')],
            },
        ),
    ]
