# Generated by Django 6.1 on 2026-09-01 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='gamification_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='reward_system_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=16)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=16)),
                ('completion_points', models.IntegerField()),
                ('late_penalty', models.IntegerField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='tasks.workspace')),
            ],
            options={
                'ordering': ['workspace_id', 'frequency', 'difficulty', 'id'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'frequency', 'difficulty'), name='unique_scoring_rule_per_workspace_frequency_difficulty')],
            },
        ),
    ]
