# Generated by Django 6.1 on 2026-09-04 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_workspace_gamification_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberScoreLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_change', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('task_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_ledger_entries', to='tasks.taskassignment')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_ledger_entries', to='tasks.workspace')),
            ],
            options={
                'ordering': ['workspace_id', 'member_id', 'created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('task_assignment',), name='unique_score_award_per_task_assignment')],
            },
        ),
    ]
