# Generated by Django 6.1 on 2026-09-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskassignment_grace_period_ends_at_and_score_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberscoreledger',
            name='transaction_type',
            field=models.CharField(choices=[('COMPLETION_SCORE', 'Completion score'), ('LATE_PENALTY', 'Late penalty'), ('GRACE_EXPIRY_PENALTY', 'Grace expiry penalty')], max_length=32),
        ),
    ]
