# Generated by Django 6.1 on 2026-09-04 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_memberscoreledger_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='reassigned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reassignment_children', to='tasks.taskassignment'),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING_ACCEPTANCE', 'ACTIVE'])), fields=('reassigned_from',), name='unique_live_reassignment_per_source'),
        ),
    ]
