# Generated by Django 6.1 on 2026-09-04 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskassignment_reassigned_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='rolled_over_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rollover_children', to='tasks.taskassignment'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='assignment_type',
            field=models.CharField(blank=True, choices=[('SELF_SELECTION', 'Self-selection'), ('MANAGER_ASSIGNMENT', 'Manager assignment'), ('REASSIGNMENT', 'Reassignment'), ('ROLLOVER', 'Daily rollover')], max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('rolled_over_from__isnull', False)), fields=('rolled_over_from',), name='unique_rollover_per_source'),
        ),
    ]
